//! Operator signatures from the ONNX specification.
//!
//! Generated from the operator documentation of ONNX 1.23.0 by
//! `tools/generate-op-schemas.py`. Do not edit.

use super::Arity::{Optional, Required, Variadic};
use super::OpSchema;

/// Every operator of the default and `ai.onnx.ml` domains, ordered by type
/// so that a lookup can binary search.
pub const SCHEMAS: &[OpSchema] = &[
    OpSchema {
        domain: "",
        op_type: "Abs",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Acos",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Acosh",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Adagrad",
        inputs: &[("R", Required), ("T", Required), ("inputs", Variadic)],
        outputs: &[("outputs", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "Adam",
        inputs: &[("R", Required), ("T", Required), ("inputs", Variadic)],
        outputs: &[("outputs", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "Add",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "AffineGrid",
        inputs: &[("theta", Required), ("size", Required)],
        outputs: &[("grid", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "And",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ArgMax",
        inputs: &[("data", Required)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ArgMin",
        inputs: &[("data", Required)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "ArrayFeatureExtractor",
        inputs: &[("X", Required), ("Y", Required)],
        outputs: &[("Z", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Asin",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Asinh",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Atan",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Atanh",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Attention",
        inputs: &[
            ("Q", Required),
            ("K", Required),
            ("V", Required),
            ("attn_mask", Optional),
            ("past_key", Optional),
            ("past_value", Optional),
            ("nonpad_kv_seqlen", Optional),
        ],
        outputs: &[
            ("Y", Required),
            ("present_key", Optional),
            ("present_value", Optional),
            ("qk_matmul_output", Optional),
        ],
    },
    OpSchema {
        domain: "",
        op_type: "AveragePool",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "BatchNormalization",
        inputs: &[
            ("X", Required),
            ("scale", Required),
            ("B", Required),
            ("input_mean", Required),
            ("input_var", Required),
        ],
        outputs: &[
            ("Y", Required),
            ("running_mean", Optional),
            ("running_var", Optional),
        ],
    },
    OpSchema {
        domain: "",
        op_type: "Bernoulli",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "Binarizer",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "BitCast",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "BitShift",
        inputs: &[("X", Required), ("Y", Required)],
        outputs: &[("Z", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "BitwiseAnd",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "BitwiseNot",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "BitwiseOr",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "BitwiseXor",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "BlackmanWindow",
        inputs: &[("size", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Cast",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "CastLike",
        inputs: &[("input", Required), ("target_type", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "CastMap",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "CategoryMapper",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "CausalConvWithState",
        inputs: &[
            ("input", Required),
            ("weight", Required),
            ("bias", Optional),
            ("past_state", Optional),
        ],
        outputs: &[("output", Required), ("present_state", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Ceil",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Celu",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "CenterCropPad",
        inputs: &[("input_data", Required), ("shape", Required)],
        outputs: &[("output_data", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Clip",
        inputs: &[("input", Required), ("min", Optional), ("max", Optional)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Col2Im",
        inputs: &[
            ("input", Required),
            ("image_shape", Required),
            ("block_shape", Required),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Compress",
        inputs: &[("input", Required), ("condition", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Concat",
        inputs: &[("inputs", Variadic)],
        outputs: &[("concat_result", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ConcatFromSequence",
        inputs: &[("input_sequence", Required)],
        outputs: &[("concat_result", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Constant",
        inputs: &[],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ConstantOfShape",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Conv",
        inputs: &[("X", Required), ("W", Required), ("B", Optional)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ConvInteger",
        inputs: &[
            ("x", Required),
            ("w", Required),
            ("x_zero_point", Optional),
            ("w_zero_point", Optional),
        ],
        outputs: &[("y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ConvTranspose",
        inputs: &[("X", Required), ("W", Required), ("B", Optional)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Cos",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Cosh",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "CumProd",
        inputs: &[("x", Required), ("axis", Required)],
        outputs: &[("y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "CumSum",
        inputs: &[("x", Required), ("axis", Required)],
        outputs: &[("y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "DFT",
        inputs: &[
            ("input", Required),
            ("dft_length", Optional),
            ("axis", Optional),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "DeformConv",
        inputs: &[
            ("X", Required),
            ("W", Required),
            ("offset", Required),
            ("B", Optional),
            ("mask", Optional),
        ],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "DepthToSpace",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "DequantizeLinear",
        inputs: &[
            ("x", Required),
            ("x_scale", Required),
            ("x_zero_point", Optional),
        ],
        outputs: &[("y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Det",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "DictVectorizer",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Div",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Dropout",
        inputs: &[
            ("data", Required),
            ("ratio", Optional),
            ("training_mode", Optional),
        ],
        outputs: &[("output", Required), ("mask", Optional)],
    },
    OpSchema {
        domain: "",
        op_type: "DynamicQuantizeLinear",
        inputs: &[("x", Required)],
        outputs: &[
            ("y", Required),
            ("y_scale", Required),
            ("y_zero_point", Required),
        ],
    },
    OpSchema {
        domain: "",
        op_type: "Einsum",
        inputs: &[("Inputs", Variadic)],
        outputs: &[("Output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Elu",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Equal",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Erf",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Exp",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Expand",
        inputs: &[("input", Required), ("shape", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "EyeLike",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "FeatureVectorizer",
        inputs: &[("X", Variadic)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Flatten",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Floor",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GRU",
        inputs: &[
            ("X", Required),
            ("W", Required),
            ("R", Required),
            ("B", Optional),
            ("sequence_lens", Optional),
            ("initial_h", Optional),
        ],
        outputs: &[("Y", Optional), ("Y_h", Optional)],
    },
    OpSchema {
        domain: "",
        op_type: "Gather",
        inputs: &[("data", Required), ("indices", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GatherElements",
        inputs: &[("data", Required), ("indices", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GatherND",
        inputs: &[("data", Required), ("indices", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Gelu",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Gemm",
        inputs: &[("A", Required), ("B", Required), ("C", Optional)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GlobalAveragePool",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GlobalLpPool",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GlobalMaxPool",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Gradient",
        inputs: &[("Inputs", Variadic)],
        outputs: &[("Outputs", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "Greater",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GreaterOrEqual",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GridSample",
        inputs: &[("X", Required), ("grid", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "GroupNormalization",
        inputs: &[("X", Required), ("scale", Required), ("bias", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "HammingWindow",
        inputs: &[("size", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "HannWindow",
        inputs: &[("size", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "HardSigmoid",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "HardSwish",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Hardmax",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Identity",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "If",
        inputs: &[("cond", Required)],
        outputs: &[("outputs", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "ImageDecoder",
        inputs: &[("encoded_stream", Required)],
        outputs: &[("image", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "Imputer",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "InstanceNormalization",
        inputs: &[("input", Required), ("scale", Required), ("B", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "IsInf",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "IsNaN",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "LRN",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "LSTM",
        inputs: &[
            ("X", Required),
            ("W", Required),
            ("R", Required),
            ("B", Optional),
            ("sequence_lens", Optional),
            ("initial_h", Optional),
            ("initial_c", Optional),
            ("P", Optional),
        ],
        outputs: &[("Y", Optional), ("Y_h", Optional), ("Y_c", Optional)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "LabelEncoder",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "LayerNormalization",
        inputs: &[("X", Required), ("Scale", Required), ("B", Optional)],
        outputs: &[("Y", Required), ("Mean", Optional), ("InvStdDev", Optional)],
    },
    OpSchema {
        domain: "",
        op_type: "LeakyRelu",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Less",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "LessOrEqual",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "LinearAttention",
        inputs: &[
            ("query", Required),
            ("key", Required),
            ("value", Required),
            ("past_state", Optional),
            ("decay", Optional),
            ("beta", Optional),
        ],
        outputs: &[("output", Required), ("present_state", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "LinearClassifier",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required), ("Z", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "LinearRegressor",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Log",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "LogSoftmax",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Loop",
        inputs: &[("M", Optional), ("cond", Optional), ("v_initial", Variadic)],
        outputs: &[("v_final_and_scan_outputs", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "LpNormalization",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "LpPool",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "MatMul",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "MatMulInteger",
        inputs: &[
            ("A", Required),
            ("B", Required),
            ("a_zero_point", Optional),
            ("b_zero_point", Optional),
        ],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Max",
        inputs: &[("data_0", Variadic)],
        outputs: &[("max", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "MaxPool",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required), ("Indices", Optional)],
    },
    OpSchema {
        domain: "",
        op_type: "MaxRoiPool",
        inputs: &[("X", Required), ("rois", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "MaxUnpool",
        inputs: &[("X", Required), ("I", Required), ("output_shape", Optional)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Mean",
        inputs: &[("data_0", Variadic)],
        outputs: &[("mean", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "MeanVarianceNormalization",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "MelWeightMatrix",
        inputs: &[
            ("num_mel_bins", Required),
            ("dft_length", Required),
            ("sample_rate", Required),
            ("lower_edge_hertz", Required),
            ("upper_edge_hertz", Required),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Min",
        inputs: &[("data_0", Variadic)],
        outputs: &[("min", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Mish",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Mod",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Momentum",
        inputs: &[("R", Required), ("T", Required), ("inputs", Variadic)],
        outputs: &[("outputs", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "Mul",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Multinomial",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Neg",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "NegativeLogLikelihoodLoss",
        inputs: &[
            ("input", Required),
            ("target", Required),
            ("weight", Optional),
        ],
        outputs: &[("loss", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "NonMaxSuppression",
        inputs: &[
            ("boxes", Required),
            ("scores", Required),
            ("max_output_boxes_per_class", Optional),
            ("iou_threshold", Optional),
            ("score_threshold", Optional),
        ],
        outputs: &[("selected_indices", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "NonZero",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "Normalizer",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Not",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "OneHot",
        inputs: &[
            ("indices", Required),
            ("depth", Required),
            ("values", Required),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "OneHotEncoder",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Optional",
        inputs: &[("input", Optional)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "OptionalGetElement",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "OptionalHasElement",
        inputs: &[("input", Optional)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Or",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "PRelu",
        inputs: &[("X", Required), ("slope", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Pad",
        inputs: &[
            ("data", Required),
            ("pads", Required),
            ("constant_value", Optional),
            ("axes", Optional),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Pow",
        inputs: &[("X", Required), ("Y", Required)],
        outputs: &[("Z", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "QLinearConv",
        inputs: &[
            ("x", Required),
            ("x_scale", Required),
            ("x_zero_point", Required),
            ("w", Required),
            ("w_scale", Required),
            ("w_zero_point", Required),
            ("y_scale", Required),
            ("y_zero_point", Required),
            ("B", Optional),
        ],
        outputs: &[("y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "QLinearMatMul",
        inputs: &[
            ("a", Required),
            ("a_scale", Required),
            ("a_zero_point", Required),
            ("b", Required),
            ("b_scale", Required),
            ("b_zero_point", Required),
            ("y_scale", Required),
            ("y_zero_point", Required),
        ],
        outputs: &[("y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "QuantizeLinear",
        inputs: &[
            ("x", Required),
            ("y_scale", Required),
            ("y_zero_point", Optional),
        ],
        outputs: &[("y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "RMSNormalization",
        inputs: &[("X", Required), ("scale", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "RNN",
        inputs: &[
            ("X", Required),
            ("W", Required),
            ("R", Required),
            ("B", Optional),
            ("sequence_lens", Optional),
            ("initial_h", Optional),
        ],
        outputs: &[("Y", Optional), ("Y_h", Optional)],
    },
    OpSchema {
        domain: "",
        op_type: "RandomNormal",
        inputs: &[],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "RandomNormalLike",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "RandomUniform",
        inputs: &[],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "RandomUniformLike",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Range",
        inputs: &[
            ("start", Required),
            ("limit", Required),
            ("delta", Required),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Reciprocal",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceL1",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceL2",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceLogSum",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceLogSumExp",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceMax",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceMean",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceMin",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceProd",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceSum",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReduceSumSquare",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("reduced", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "RegexFullMatch",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Relu",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Reshape",
        inputs: &[("data", Required), ("shape", Required)],
        outputs: &[("reshaped", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Resize",
        inputs: &[
            ("X", Required),
            ("roi", Optional),
            ("scales", Optional),
            ("sizes", Optional),
        ],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ReverseSequence",
        inputs: &[("input", Required), ("sequence_lens", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "RoiAlign",
        inputs: &[
            ("X", Required),
            ("rois", Required),
            ("batch_indices", Required),
        ],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "RotaryEmbedding",
        inputs: &[
            ("X", Required),
            ("cos_cache", Required),
            ("sin_cache", Required),
            ("position_ids", Optional),
        ],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Round",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "STFT",
        inputs: &[
            ("signal", Required),
            ("frame_step", Required),
            ("window", Optional),
            ("frame_length", Optional),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "SVMClassifier",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required), ("Z", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "SVMRegressor",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "Scaler",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Scan",
        inputs: &[("initial_state_and_scan_inputs", Variadic)],
        outputs: &[("final_state_and_scan_outputs", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "ScatterElements",
        inputs: &[
            ("data", Required),
            ("indices", Required),
            ("updates", Required),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ScatterND",
        inputs: &[
            ("data", Required),
            ("indices", Required),
            ("updates", Required),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Selu",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SequenceAt",
        inputs: &[("input_sequence", Required), ("position", Required)],
        outputs: &[("tensor", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SequenceConstruct",
        inputs: &[("inputs", Variadic)],
        outputs: &[("output_sequence", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SequenceEmpty",
        inputs: &[],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SequenceErase",
        inputs: &[("input_sequence", Required), ("position", Optional)],
        outputs: &[("output_sequence", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SequenceInsert",
        inputs: &[
            ("input_sequence", Required),
            ("tensor", Required),
            ("position", Optional),
        ],
        outputs: &[("output_sequence", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SequenceLength",
        inputs: &[("input_sequence", Required)],
        outputs: &[("length", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SequenceMap",
        inputs: &[
            ("input_sequence", Required),
            ("additional_inputs", Variadic),
        ],
        outputs: &[("out_sequence", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "Shape",
        inputs: &[("data", Required)],
        outputs: &[("shape", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Shrink",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Sigmoid",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Sign",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Sin",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Sinh",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Size",
        inputs: &[("data", Required)],
        outputs: &[("size", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Slice",
        inputs: &[
            ("data", Required),
            ("starts", Required),
            ("ends", Required),
            ("axes", Optional),
            ("steps", Optional),
        ],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Softmax",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SoftmaxCrossEntropyLoss",
        inputs: &[
            ("scores", Required),
            ("labels", Required),
            ("weights", Optional),
        ],
        outputs: &[("output", Required), ("log_prob", Optional)],
    },
    OpSchema {
        domain: "",
        op_type: "Softplus",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Softsign",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SpaceToDepth",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Split",
        inputs: &[("input", Required), ("split", Optional)],
        outputs: &[("outputs", Variadic)],
    },
    OpSchema {
        domain: "",
        op_type: "SplitToSequence",
        inputs: &[("input", Required), ("split", Optional)],
        outputs: &[("output_sequence", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Sqrt",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Squeeze",
        inputs: &[("data", Required), ("axes", Optional)],
        outputs: &[("squeezed", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "StringConcat",
        inputs: &[("X", Required), ("Y", Required)],
        outputs: &[("Z", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "StringNormalizer",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "StringSplit",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required), ("Z", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Sub",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Sum",
        inputs: &[("data_0", Variadic)],
        outputs: &[("sum", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "SwiGLU",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Swish",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Tan",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Tanh",
        inputs: &[("input", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "TensorScatter",
        inputs: &[
            ("past_cache", Required),
            ("update", Required),
            ("write_indices", Optional),
        ],
        outputs: &[("present_cache", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "TfIdfVectorizer",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "ThresholdedRelu",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Tile",
        inputs: &[("input", Required), ("repeats", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "TopK",
        inputs: &[("X", Required), ("K", Required)],
        outputs: &[("Values", Required), ("Indices", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Transpose",
        inputs: &[("data", Required)],
        outputs: &[("transposed", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "TreeEnsemble",
        inputs: &[("X", Required)],
        outputs: &[("Y", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Trilu",
        inputs: &[("input", Required), ("k", Optional)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Unique",
        inputs: &[("X", Required)],
        outputs: &[
            ("Y", Required),
            ("indices", Optional),
            ("inverse_indices", Optional),
            ("counts", Optional),
        ],
    },
    OpSchema {
        domain: "",
        op_type: "Unsqueeze",
        inputs: &[("data", Required), ("axes", Required)],
        outputs: &[("expanded", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Where",
        inputs: &[("condition", Required), ("X", Required), ("Y", Required)],
        outputs: &[("output", Required)],
    },
    OpSchema {
        domain: "",
        op_type: "Xor",
        inputs: &[("A", Required), ("B", Required)],
        outputs: &[("C", Required)],
    },
    OpSchema {
        domain: "ai.onnx.ml",
        op_type: "ZipMap",
        inputs: &[("X", Required)],
        outputs: &[("Z", Required)],
    },
];
